import React from 'react';
// FIX: Use namespace import for react-router-dom to resolve module export errors.
import * as ReactRouterDOM from 'react-router-dom';
import Layout from '../components/Layout';

const CopyrightPage = () => {
  return (
    <Layout>
      <div className="max-w-4xl mx-auto bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8">
        <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-6 font-serif">Copyright Information</h1>
        <div className="prose dark:prose-invert max-w-none text-gray-800 dark:text-gray-200">
          <p className="text-lg">Effective Date: {new Date().toLocaleDateString()}</p>
          <p>
            <strong>Disclaimer:</strong> This is a general template for a copyright page and does not constitute legal advice. You should consult with a legal professional to draft a policy that is appropriate for your specific circumstances.
          </p>

          <h2 className="text-2xl font-bold mt-8">Ownership of Content</h2>
          <p>
            All content on Limra InfoNet, including text, graphics, logos, images, and the compilation thereof, is the property of Limra InfoNet or its content suppliers and is protected by international copyright laws.
          </p>
          <p>
            The content generated by artificial intelligence (AI) is created under the direction and creative control of our editorial team. As such, the resulting work is considered the intellectual property of Limra InfoNet.
          </p>

          <h2 className="text-2xl font-bold mt-8">Permitted Use</h2>
          <p>
            You are granted a limited license to access and make personal use of this website. You may do the following:
          </p>
          <ul>
            <li>View and read the content for your own personal, non-commercial use.</li>
            <li>Share links to our articles on social media or other websites.</li>
            <li>Quote short excerpts from our content, provided that you give clear and proper attribution to Limra InfoNet with a link back to the original article.</li>
          </ul>

          <h2 className="text-2xl font-bold mt-8">Prohibited Use</h2>
          <p>
            You may not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store, or transmit any of the material on our website without the prior written consent of Limra InfoNet.
          </p>
          
          <h2 className="text-2xl font-bold mt-8">Copyright Infringement</h2>
          <p>
            If you believe that any content on our website violates your copyright, please notify us by providing a written notice. You can reach us via our <ReactRouterDOM.Link to="/contact" className="text-primary-500 hover:underline">Contact Page</ReactRouterDOM.Link>.
          </p>
        </div>
      </div>
    </Layout>
  );
};

export default CopyrightPage;